type DDD = {
  ddd: number;
  cidade: string;
  uf: string;
};

export const DDD_VALIDOS: DDD[] = [
  { ddd: 11, cidade: 'São Paulo', uf: 'SP' },
  { ddd: 12, cidade: 'São José dos Campos', uf: 'SP' },
  { ddd: 13, cidade: 'Santos', uf: 'SP' },
  { ddd: 14, cidade: 'Bauru', uf: 'SP' },
  { ddd: 15, cidade: 'Sorocaba', uf: 'SP' },
  { ddd: 16, cidade:' Ribeirão Preto', uf: 'SP' },
  { ddd: 17, cidade: 'São José do Rio Preto', uf: 'SP' },
  { ddd: 18, cidade: 'Presidente Prudente', uf: 'SP' },
  { ddd: 19, cidade: 'Campinas', uf: 'SP' },
  { ddd: 21, cidade: 'Rio de Janeiro', uf: 'RJ' },
  { ddd: 22, cidade: 'Campos dos Goytacazes', uf: 'RJ' },
  { ddd: 24, cidade: 'Volta Redonda', uf: 'RJ' },
  { ddd: 27, cidade: 'Vila Velha/Vitória', uf: 'ES' },
  { ddd: 28, cidade: 'Cachoeiro de Itapemirim', uf: 'ES' },
  { ddd: 31, cidade: 'Belo Horizonte', uf: 'MG' },
  { ddd: 32, cidade: 'Juiz de Fora', uf: 'MG' },
  { ddd: 33, cidade: 'Governador Valadares', uf: 'MG' },
  { ddd: 34, cidade: 'Uberlândia', uf: 'MG' },
  { ddd: 35, cidade: 'Poços de Caldas', uf: 'MG' },
  { ddd: 37, cidade: 'Divinópolis', uf: 'MG' },
  { ddd: 38, cidade: 'Montes Claros', uf: 'MG' },
  { ddd: 41, cidade: 'Curitiba', uf: 'PR' },
  { ddd: 42, cidade: 'Ponta Grossa', uf: 'PR' },
  { ddd: 43, cidade: 'Londrina', uf: 'PR' },
  { ddd: 44, cidade: 'Maringá', uf: 'PR' },
  { ddd: 45, cidade: 'Foz do Iguaçú', uf: 'PR' },
  { ddd: 46, cidade: 'Francisco Beltrão/Pato Branco', uf: 'PR' },
  { ddd: 47, cidade: 'Joinville', uf: 'SC' },
  { ddd: 48, cidade: 'Florianópolis', uf: 'SC' },
  { ddd: 49, cidade: 'Chapecó', uf: 'SC' },
  { ddd: 51, cidade: 'Porto Alegre', uf: 'RS' },
  { ddd: 53, cidade: 'Pelotas', uf: 'RS' },
  { ddd: 54, cidade: 'Caxias do Sul', uf: 'RS' },
  { ddd: 55, cidade: 'Santa Maria', uf: 'RS' },
  { ddd: 61, cidade: 'Brasília', uf: 'DF' },
  { ddd: 62, cidade: 'Goiânia', uf: 'GO' },
  { ddd: 63, cidade: 'Palmas', uf: 'TO' },
  { ddd: 64, cidade: 'Rio Verde', uf: 'GO' },
  { ddd: 65, cidade: 'Cuiabá', uf: 'MT' },
  { ddd: 66, cidade: 'Rondonópolis', uf: 'MT' },
  { ddd: 67, cidade: 'Campo Grande', uf: 'MS' },
  { ddd: 68, cidade: 'Rio Branco', uf: 'AC' },
  { ddd: 69, cidade: 'Porto Velho', uf: 'RO' },
  { ddd: 71, cidade: 'Salvador', uf: 'BA' },
  { ddd: 73, cidade: 'Ilhéus', uf: 'BA' },
  { ddd: 74, cidade: 'Juazeiro', uf: 'BA' },
  { ddd: 75, cidade: 'Feira de Santana', uf: 'BA' },
  { ddd: 77, cidade: 'Barreiras', uf: 'BA' },
  { ddd: 79, cidade: 'Aracaju', uf: 'SE' },
  { ddd: 81, cidade: 'Recife', uf: 'PE' },
  { ddd: 82, cidade: 'Maceió', uf: 'AL' },
  { ddd: 83, cidade: 'João Pessoa', uf: 'PB' },
  { ddd: 84, cidade: 'Natal', uf: 'RN' },
  { ddd: 85, cidade: 'Fortaleza', uf: 'CE' },
  { ddd: 86, cidade: 'Teresina', uf: 'PI' },
  { ddd: 87, cidade: 'Petrolina', uf: 'PE' },
  { ddd: 88, cidade: 'Juazeiro do Norte', uf: 'CE' },
  { ddd: 89, cidade: 'Picos', uf: 'PI' },
  { ddd: 91, cidade: 'Belém', uf: 'PA' },
  { ddd: 92, cidade: 'Manaus', uf: 'AM' },
  { ddd: 93, cidade: 'Santarém', uf: 'PA' },
  { ddd: 94, cidade: 'Marabá', uf: 'PA' },
  { ddd: 95, cidade: 'Boa Vista', uf: 'RR' },
  { ddd: 96, cidade: 'Macapá', uf: 'AP' },
  { ddd: 97, cidade: 'Coari', uf: 'AM' },
  { ddd: 98, cidade: 'São Luís', uf: 'MA' },
  { ddd: 99, cidade: 'Imperatriz', uf: 'MA' }
];
